In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, f1_score
from sklearn.linear_model import LogisticRegressionCV

import scikitplot.plotters as skplt

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("../data/creditcard.csv")
X = np.array(df.filter(regex="V.*"))
y = np.array(df.Class)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify = y)

In [4]:
LR = LogisticRegressionCV(class_weight= "balanced")
LR.fit(X_train, y_train)

LogisticRegressionCV(Cs=10, class_weight='balanced', cv=None, dual=False,
           fit_intercept=True, intercept_scaling=1.0, max_iter=100,
           multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
           refit=True, scoring=None, solver='lbfgs', tol=0.0001, verbose=0)

In [5]:
#fig1 = plt.figure()
skplt.precision_recall_curve(y_test, LR.predict_proba(X_test)[:,1])

(array([ 0.00207442,  0.00206164,  0.00206167, ...,  1.        ,
         1.        ,  1.        ]),
 array([ 1.        ,  0.99382716,  0.99382716, ...,  0.01234568,
         0.00617284,  0.        ]),
 array([ 0.03146394,  0.03146434,  0.03146462, ...,  1.        ,
         1.        ,  1.        ]))

In [5]:
import scikitplot

In [6]:
scikitplot.__version__

u'0.2.7'

In [6]:
?skplt.precision_recall_curve